Fixes to let counter example compile
emorydunn/StreamDeckPlugin pull request #19
Opened 2023-05-06 18:09 UTC by RomanBaiocco

On the main branch, if I cd into `Example/counter` and run `swift build` I am unable to compile the plugin due to some errors. These changes fix those errors.

2023-05-06 18:49 UTC, emorydunn requested changes
Thanks for fixing the package manifest. I've added some comments to the actions.

2023-05-06 18:49 UTC, emorydunn commented on Examples/counter/Sources/counter/Actions/DecrementAction.swift
Remove the `controllers` and `encoder` properties and instead conform the class to `KeyAction`.

2023-05-06 18:49 UTC, emorydunn commented on Examples/counter/Sources/counter/Actions/IncrementAction.swift
Remove the `controllers` and `encoder` properties and instead conform the class to `KeyAction`.

2023-05-07 06:08 UTC, RomanBaiocco commented
Just tried again! Let me know if I did it incorrectly, this is literally the first thing I've done after getting the basics of the language down 😅

2023-05-07 14:48 UTC, emorydunn approved these changes

2023-05-07 14:53 UTC, merged